services:
  client-sba:
      image: eclipse-temurin:21-jdk
      container_name: client-sba
      ports:
        - 8081:8080
        - 8001:8000
      expose:
        - "8001"
      depends_on:
        - clientdb
      networks:
        - my-net
      extra_hosts:
      - "host.docker.internal:host-gateway"
      volumes:
        - ./build/libs/fastgo_client-0.0.1-SNAPSHOT.jar:/app/app.jar
      working_dir: /app
      entrypoint: >
        java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  clientdb:
    image: mongo:5.0
    container_name: clientdb
    ports:
        - 27018:27017
    networks:
          - my-net

networks:
      my-net:
        driver:
         'bridge'
